### ISSUE TITLE
Unable to Install hassio add-on

### ISSUE THREAD

**Issue by mschwerz** [donetick/hassio-addons#3]
I am looking to install the selfhosted HA addon and seem to be having difficulty getting it to install. I keep getting the following error: 
Failed to to call /addons/2c57906a_Donetick/install - Can't install ghcr.io/donetick/amd64-hassio-addons:1.0.4: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/donetick/amd64-hassio-addons:1.0.4/json: Not Found ("No such image: ghcr.io/donetick/amd64-hassio-addons:1.0.4")

It is odd since I can see it there at https://github.com/donetick/hassio-addons/pkgs/container/amd64-hassio-addons/249827656?tag=1.0.4

Is there something I am doing wrong to get it installed properly?

Love the project btw!

**Comment by mschwerz** [comment]
I will mention I did manage to get it to work in Home Assistant, but not without pretty much building the add on locally. I had to update the config.yaml to point to the latest release from the original repo and remove instances pointing the github registry for the docker image.

I am unable to pull the docker image at all from the github registry.

**Comment by meauxt** [comment]
I will take a look at it today!

**Comment by meauxt** [comment]
@mschwerz it should be resolved with version 1.0.6. if not let me know!

**Comment by meauxt** [comment]
I am going to close this. if you are still facing an issue please feel free to reopen this!

**Comment by mschwerz** [comment]
Hey sorry to get back late! Yes it is working thanks!
